#!/usr/bin/env python3
"""
Show variable transformation through CBottleInfill
==================================================

This script shows what variables go in and come out of CBottleInfill
without requiring model loading or data fetching.
"""

# CBottle requires these 45 variables
CBOTTLE_REQUIRED = [
    # Surface variables (13)
    'tcwv', 'tclw', 'tciw', 't2m', 'u10m', 'v10m', 'rlut', 'rsut',
    'msl', 'tpf', 'rsds', 'sst', 'sic',
    # Pressure levels: u, v, t, z at 1000, 850, 700, 500, 300, 200, 50, 10 hPa (32 vars)
    'u1000', 'u850', 'u700', 'u500', 'u300', 'u200', 'u50', 'u10',
    'v1000', 'v850', 'v700', 'v500', 'v300', 'v200', 'v50', 'v10',
    't1000', 't850', 't700', 't500', 't300', 't200', 't50', 't10',
    'z1000', 'z850', 'z700', 'z500', 'z300', 'z200', 'z50', 'z10',
]

# What we typically use as input from ERA5
ERA5_INPUT = [
    'u10m', 'v10m', 't2m', 'msl',
    'z50', 'u50', 'v50',
    'z500', 'u500', 'v500',
    'z1000', 'u1000', 'v1000',
]

# What CBottleInfill outputs (all 45 CBottle variables)
CBOTTLE_INFILL_OUTPUT = CBOTTLE_REQUIRED

print("=" * 80)
print("CBottleInfill Variable Transformation")
print("=" * 80)

print(f"\n{'INPUT (from ERA5)':<40} → OUTPUT (CBottleInfill)")
print("=" * 80)

print(f"\n{len(ERA5_INPUT)} variables IN")
print("-" * 80)
for var in sorted(ERA5_INPUT):
    print(f"  {var}")

print(f"\n{len(CBOTTLE_INFILL_OUTPUT)} variables OUT")
print("-" * 80)
for var in sorted(CBOTTLE_INFILL_OUTPUT):
    marker = "  " if var in ERA5_INPUT else "✓ "  # ✓ marks newly generated
    print(f"{marker}{var}")

print("\n" + "=" * 80)
print("Variables GENERATED by CBottleInfill (not in ERA5 input)")
print("=" * 80)

generated = set(CBOTTLE_INFILL_OUTPUT) - set(ERA5_INPUT)
print(f"\n{len(generated)} variables generated:")

# Categorize
surface_gen = sorted([v for v in generated if not any(c.isdigit() for c in v)])
pressure_gen = sorted([v for v in generated if any(c.isdigit() for c in v)])

print(f"\nSurface variables ({len(surface_gen)}):")
surface_descriptions = {
    'tclw': 'Total cloud liquid water',
    'tciw': 'Total cloud ice water',
    'rlut': 'Outgoing longwave radiation (TOA)',
    'rsut': 'Outgoing shortwave radiation (TOA)',
    'rsds': 'Downwelling shortwave radiation (surface)',
    'tpf': 'Total precipitation flux',
    'sic': 'Sea ice concentration',
    'tcwv': 'Total column water vapor',
    'sst': 'Sea surface temperature',
}
for var in surface_gen:
    desc = surface_descriptions.get(var, '')
    print(f"  • {var:<8} {desc}")

print(f"\nPressure level variables ({len(pressure_gen)}):")
from collections import defaultdict
by_param = defaultdict(list)
for var in pressure_gen:
    param = ''.join([c for c in var if not c.isdigit()])
    level = int(''.join([c for c in var if c.isdigit()]))
    by_param[param].append(level)

for param, levels in sorted(by_param.items()):
    param_names = {
        'u': 'Zonal wind',
        'v': 'Meridional wind',
        't': 'Temperature',
        'z': 'Geopotential height'
    }
    print(f"  • {param:<2} ({param_names.get(param, 'Unknown')}): levels {sorted(levels)} hPa")

print("\n" + "=" * 80)
print("PROOF THAT CBottleInfill IS NECESSARY")
print("=" * 80)

print(f"""
CBottleVideo requires:  {len(CBOTTLE_REQUIRED)} variables
ERA5 provides:          {len(ERA5_INPUT)} variables ({100*len(ERA5_INPUT)/len(CBOTTLE_REQUIRED):.1f}% coverage)
CBottleInfill fills:    {len(generated)} missing variables ({100*len(generated)/len(CBOTTLE_REQUIRED):.1f}% of requirements)

Without CBottleInfill:
  ✗ Cannot use ERA5 for conditional generation
  ✗ Missing critical physics variables (radiation, clouds, precipitation)
  ✗ Incomplete atmospheric state (missing many pressure levels)

With CBottleInfill:
  ✓ Generates all {len(CBOTTLE_REQUIRED)} required variables from just {len(ERA5_INPUT)} inputs
  ✓ Uses physics learned from ICON to infer radiation, clouds, precipitation
  ✓ Enables realistic conditional forecasting with ERA5 initial conditions
""")

print("=" * 80)
print("\nCODE USED IN EXAMPLES:")
print("=" * 80)
print("""
# Input: 13 ERA5 variables
input_variables = [
    "u10m", "v10m", "t2m", "msl",
    "z50", "u50", "v50",
    "z500", "u500", "v500",
    "z1000", "u1000", "v1000",
]

# Fetch from ERA5
era5_x, era5_coords = fetch_data(era5_ds, times, input_variables, device=device)
print(f"ERA5 provides: {len(era5_coords['variable'])} variables")

# Run CBottleInfill
cbottle_infill = CBottleInfill.load_model(package, input_variables=input_variables)
infilled_x, infilled_coords = cbottle_infill(era5_x, era5_coords)
print(f"CBottleInfill outputs: {len(infilled_coords['variable'])} variables")

# Result: 13 → 45 variables
""")
